### ISSUE TITLE
Average does not change, when sensor does not update for a while

### ISSUE THREAD

**Issue by KillerTic** [Limych/ha-average#22]
This sensor is great and I want to primarily use it to calculate the autarky I have due to solar power.
There is a live autarky sensor I have integrated.

My issue is, that this sensor changes to 0 once no sun is out and the battery is empty. Then it stays on this value until it is charged again. It does not send any updates. Now I have a time frame from 11:47 pm until 9:53 am, which is only represented by one value.
This is 0 and should drive down the average quite significantly.

Any chance to take the timeframe a value has not changed into account?

**Comment by Limych** [comment]
The principle of operation of my component: if a time period is specified in the settings in any form, the sensor updates its value regularly every 30 seconds (set by HA itself). Otherwise, the sensor value is updated with any update of any of the source sensors. there is no point in recalculating the value - it will still remain unchanged.

So the logic of the component is correct. There are no bugs.

Unfortunately, you ignored the bug report template and did not provide more details. As a result, I cannot help you with anything else.
