### ISSUE TITLE
Define what average this sensor calculates

### ISSUE THREAD

**Issue by JohanBraeken** [Limych/ha-average#77]
It is unclear to me what kind of average this sensor calculates.

The "average" temperature for a timperiod (Ex: Average temperature of a day) is normaly just a single value and thus a horizontal line on a graph. (The average has no real timestamp itself, it is the average that is valid over the entire timerange.)

At first sight it seems what is being calculated is a moving average for a certain timeperiod, and the calculated average value is updated when the corresponding sensor value changes.
(This average is timestamped with the time of calculation, and hence the changes of average in the graph.)

However, I'm greatly confused by the screenshot in the README.md: [Temperature 48h](https://raw.githubusercontent.com/Limych/ha-average/dev/example.png)

Near the end of the graph, you see the actual outdoor temperature is below average and still decreasing.
However, the average temperature is rising during that same period, which is the oposite of what is expected from an average.

Is this a bug? Or what kind of average does this sensor calculate?

**Comment by Limych** [comment]
The sensor does not know how to look into the future. Therefore, the average temperature per day can be one value only if it is data for the past day.
If you set the settings for calculating the average temperature value for the current day, the value will not be the same value - it will be different at each time of that day, because new values ​​will be regularly added, which will be taken into account in the sensor: in other words, it will calculate the average from the beginning of the day to the current time.

On the chart you are referring to, the average is changing, because there is the calculation of the average for the last 48 hours FROM THE MOMENT OF CALCULATION - the initial data window is shifted in time every second. Hence, the average value of these data changes every second.

So, there are no bugs... All correct.

**Comment by Limych** [comment]
See detailed information about time periods here: https://github.com/Limych/ha-average#time-periods
